# Generated by Django 5.1.4 on 2025-03-21 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Administracao', '0004_alter_setorescad_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicosCad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=3, verbose_name='Sigla')),
                ('N_Servico', models.CharField(max_length=50, verbose_name='Serviços')),
                ('status', models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], default='Ativo', max_length=8)),
                ('servicos', models.ManyToManyField(related_name='Servico_Setores', to='Administracao.setorescad')),
            ],
        ),
    ]
