# Generated by Django 5.1.4 on 2025-03-24 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administracao', '0004_alter_setorescad_nome'),
        ('Configuracoes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicoscad',
            name='servicos',
        ),
        migrations.CreateModel(
            name='LocaisCad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('N_Local', models.CharField(max_length=50, verbose_name='Serviços')),
                ('status', models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], default='Ativo', max_length=8)),
                ('setores', models.ManyToManyField(related_name='Servico_Setores', to='Administracao.setorescad')),
            ],
        ),
    ]
