# Generated by Django 5.1.4 on 2025-03-24 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administracao', '0004_alter_setorescad_nome'),
        ('Configuracoes', '0002_remove_servicoscad_servicos_locaiscad'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicoscad',
            name='setores',
            field=models.ManyToManyField(related_name='Servico_Setores', to='Administracao.setorescad'),
        ),
        migrations.AlterField(
            model_name='locaiscad',
            name='setores',
            field=models.ManyToManyField(related_name='Servico_Locais', to='Administracao.setorescad'),
        ),
    ]
