# Generated by Django 5.1.4 on 2025-03-24 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configuracoes', '0003_servicoscad_setores_alter_locaiscad_setores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicoscad',
            name='status',
            field=models.CharField(blank=True, choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], default='Ativo', max_length=8, null=True),
        ),
    ]
