# Generated by Django 5.1.6 on 2025-02-06 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administracao', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setorescad',
            options={'verbose_name': 'Setor', 'verbose_name_plural': 'Setores'},
        ),
    ]
