# Generated by Django 5.1.4 on 2025-03-21 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administracao', '0002_alter_setorescad_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setorescad',
            options={},
        ),
        migrations.AlterField(
            model_name='setorescad',
            name='nome',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
