# Generated by Django 5.1.4 on 2025-03-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administracao', '0003_alter_setorescad_options_alter_setorescad_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setorescad',
            name='nome',
            field=models.CharField(max_length=50, unique=True, verbose_name='Setor'),
        ),
    ]
