# Generated by Django 5.1.4 on 2025-04-15 18:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Configuracoes', '0004_alter_servicoscad_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SenhasCad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('codigo', models.CharField(max_length=10)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('data_emissao', models.DateTimeField(default=django.utils.timezone.now)),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Serviço', to='Configuracoes.servicoscad')),
            ],
            options={
                'ordering': ['-data_emissao'],
                'unique_together': {('servico', 'numero')},
            },
        ),
    ]
